# Generated by Django 3.1.6 on 2021-02-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Companie', max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
